-- Create the table
create table public.buses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  photo text,
  plate_number text not null,
  make_model text not null,
  seats integer,
  seat_scheme_url text,
  vin text,
  docs_url text,
  vehicle_insurance_expiry date,
  passenger_insurance_expiry date,
  maintenance_expiry date,
  tachograph_expiry date,
  fire_extinguisher_expiry date,
  first_aid_expiry date
);

-- Set up Row Level Security (RLS)
-- For development purposes, we will allow open access. 
-- IN PRODUCTION: You should restrict this based on authentication.
alter table public.buses enable row level security;

create policy "Enable read access for all users"
on public.buses for select
to anon
using (true);

create policy "Enable insert access for all users"
on public.buses for insert
to anon
with check (true);

create policy "Enable update access for all users"
on public.buses for update
to anon
using (true);

create policy "Enable delete access for all users"
on public.buses for delete
to anon
using (true);
